#include "main.h"


// EEPROM Memory map
#define EE_ADR_BYTE__SET_DEFAULT					0x00

#define EE_ADR_WORD__G_MAX_CLOSING_TIME_MS			0x01
#define EE_ADR_WORD__G_MAX_OPENING_TIME_MS			0x03
#define EE_ADR_WORD__G_MAX_DOOR_OPEN_TIME_SEC		0x05

#define EE_ADR_WORD__G_WARNING_TIME_MS				0x07
#define EE_ADR_WORD__G_WARNING_BEEP_ON_TIME_MS		0x09
#define EE_ADR_WORD__G_WARNING_BEEP_OFF_TIME_MS		0x0B
#define EE_ADR_WORD__G_WARNING_LIGHT_ON_TIME_MS		0x0D
#define EE_ADR_WORD__G_WARNING_LIGHT_OFF_TIME_MS	0x0F
#define EE_ADR_WORD__G_WARNINGS_ENABLED_DELAY_MS	0x11
#define EE_ADR_WORD__G_TIME_BETWEEN_COMMANDS_MS		0x13
#define EE_ADR_WORD__G_WARNING_DOOR_OPEN_BEEP_ON_TIME_MS		0x15
#define EE_ADR_WORD__G_WARNING_DOOR_OPEN_BEEP_OFF_TIME_MS		0x17
#define EE_ADR_WORD__G_WARNING_DOOR_OPEN_LIGHT_ON_TIME_MS		0x19
#define EE_ADR_WORD__G_WARNING_DOOR_OPEN_LIGHT_OFF_TIME_MS		0x1B
#define EE_ADR_STRING_PILOT_CODE_OPEN				0x0100
#define EE_ADR_STRING_PILOT_CODE_CLOSE				0x0140
#define EE_ADR_STRING_PILOT_CODE_OPEN_2				0x0180
#define EE_ADR_STRING_PILOT_CODE_CLOSE_2			0x01C0
#define EE_ADR_STRING_PILOT_CODE_OPEN_3				0x0200
#define EE_ADR_STRING_PILOT_CODE_CLOSE_3			0x0240

// Functions
void ee_init(void);
void ee_clear(void);
void ee_clear_block(uint16_t, uint16_t);
